# setup staging and production hosts

- name: Install and run go app on servers
  vars:
    env: "staging"
    workdir: "/var/lib/jenkins/workspace/simple-go-jenkins-app_main"
  hosts: "{{ env }}"
  become: yes
  tasks:
  - name: Install go
    yum:
      name: go
      state: present
  - name: Create app directory
    file:
      path: /app
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0755
  - name: Copy go app from local to remote
    copy:
      src: "{{ workdir }}/dist/go-app"
      dest: /app/go-app
      owner: jenkins
      group: jenkins
      mode: 0755
  - name: Copy index.html from local to remote
    copy:
      src: "{{ workdir }}/index.html"
      dest: /app/index.html
      owner: jenkins
      group: jenkins
      mode: 0755
  - name: Copy the assets folder from local to remote
    copy:
      src: "{{ workdir }}/assets"
      dest: /app/assets
      owner: jenkins
      group: jenkins
      mode: 0755
  - name: Copy .env file from local to remote
    copy:
      src: "{{ workdir }}/.env"
      dest: /app/.env
      owner: jenkins
      group: jenkins
      mode: 0755
  - name: expose go app port 3000
    firewalld:
      port: 3000/tcp
      permanent: yes
      state: enabled
      immediate: yes
  - name: Run go app in background
    shell: nohup /app/go-app > /dev/null 2>&1 &
    register: result
    failed_when: result.rc != 0
    changed_when: false
  - name: Check that go app is running
    uri:
      url: http://localhost:3000
      status_code: 200
    register: result
    failed_when: result.status != 200
    changed_when: false
