# setup staging and production hosts

- name: Setup staging and production hosts
  hosts: "{{ env }}"
  become: yes
  tasks:
    - name: Update yum
      yum:
        name: '*'
        state: latest
        skip_broken: yes
  
    - name: Install git
      yum:
        name: git
        state: present

    - name: Install yum utils
      yum:
        name: yum-utils
        state: present

    - name: Add docker-ce repo for centos
      yum_repository:
        name: docker-ce
        description: Docker CE Stable - x86_64
        baseurl: https://download.docker.com/linux/centos/8/x86_64/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install docker-ce
      yum:
        name: docker-ce
        state: present
        allowerasing: yes

    - name: Install docker-ce-cli
      yum:
        name: docker-ce-cli
        state: present
        allowerasing: yes

    - name: Install containerd.io
      yum:
        name: containerd.io
        state: present
        allowerasing: yes

    - name: Make docker start on boot
      systemd:
        name: docker
        enabled: yes

    - name: Add docker group
      group:
        name: docker
        state: present

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Start docker service
      systemd:
        name: docker
        state: started

    - name: Expose port 3000
      firewalld:
        port: 3000/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Use pip3 to install docker
      pip:
        name: docker
        executable: pip3

    - name: Stop and remove old container
      docker_container:
        name: simple-go-jenkins
        state: absent
      ignore_errors: yes

    - name: Run new container, expose port 3000 and pull image from docker hub
      docker_container:
        name: simple-go-jenkins
        image: "2464410/simple-go-jenkins:{{ commit_id }}"
        state: started
        ports:
          - "3000:3000"
        restart_policy: always
