# setup staging and production hosts

- name: Install and run go app on servers
  vars:
    env: "staging"
  hosts: "{{ env }}"
  become: yes
  tasks:
  - name: Install go
    yum:
      name: go
      state: present
  - name: Create app directory
    file:
      path: /app
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0755
  - name: Copy go app from local to remote
    copy:
      src: ./dist/go-app
      dest: /app/go-app
      owner: jenkins
      group: jenkins
      mode: 0755
  - name: expose go app port 3000
    firewalld:
      port: 3000/tcp
      permanent: yes
      state: enabled
      immediate: yes
  - name: Run go app
    shell: /app/go-app
  - name: Check that go app is running
    shell: ps -ef | grep go-app
    register: result
    failed_when: "'go-app' not in result.stdout"
    changed_when: false
  - name: Ping localhost to check if go app is running
    uri:
      url: http://localhost:3000
      status_code: 200
    register: result
    failed_when: result.status != 200
    changed_when: false